-- Kitchen & Bath Lab 모바일 예약마감/재오픈 기능
-- 관리자 비밀번호는 기존 모바일 프로젝트 값인 930707을 유지합니다.

create table if not exists public.booking_slots (
  id bigint generated by default as identity primary key,
  booking_date date not null,
  booking_time time not null,
  source text not null check (source in ('booked', 'admin')),
  created_at timestamptz not null default now(),
  unique (booking_date, booking_time)
);

alter table public.booking_slots enable row level security;

grant select on public.booking_slots to anon, authenticated;

grant usage, select on sequence public.booking_slots_id_seq to anon, authenticated;

create or replace function public.admin_set_slot(
  p_date date,
  p_time time,
  p_closed boolean,
  p_password text
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
begin
  if p_password <> '930707' then
    return false;
  end if;

  if p_closed then
    if exists (
      select 1 from public.booking_slots
      where booking_date = p_date
        and booking_time = p_time
        and source = 'booked'
    ) then
      return false;
    end if;

    insert into public.booking_slots (booking_date, booking_time, source)
    values (p_date, p_time, 'admin')
    on conflict (booking_date, booking_time)
    do update set source = 'admin';
  else
    delete from public.booking_slots
    where booking_date = p_date
      and booking_time = p_time
      and source = 'admin';
  end if;

  return true;
end;
$$;

grant execute on function public.admin_set_slot(date, time, boolean, text) to anon, authenticated;

-- 예약 신청이 슬롯 테이블에 기록될 수 있도록 예약 함수도 안전하게 유지합니다.
create or replace function public.reserve_booking(p_date date, p_time time, p_name text, p_phone text, p_service text)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  new_token uuid;
begin
  if btrim(coalesce(p_name, '')) = ''
    or btrim(coalesce(p_phone, '')) = ''
    or btrim(coalesce(p_service, '')) = '' then
    return null;
  end if;

  insert into public.booking_slots (booking_date, booking_time, source)
  values (p_date, p_time, 'booked');

  insert into public.bookings (booking_date, booking_time, name, phone, service)
  values (p_date, p_time, btrim(p_name), btrim(p_phone), btrim(p_service))
  returning review_token into new_token;

  return new_token;
exception when unique_violation then
  return null;
end;
$$;

grant execute on function public.reserve_booking(date, time, text, text, text) to anon, authenticated;
